language: cpp

# need at least gcc 4.8 for -std=c++11
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

# use gcc-4.8
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script: autoreconf -f -i -s && ./configure --without-gtest && make && make check

compiler:
- clang
- gcc
