name: "CI Unit Tests"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Normal:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install meson and ninja
      run: pip3 install --user meson ninja
    - name: Run Unit Tests
      run: |
        export PATH=${HOME}/.local/bin:${PATH}
        meson setup -Dbuildtype=release build
        meson compile -C build
        build/capn-test

  Sanitizers:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install meson and ninja
      run: pip3 install --user meson ninja
    - name: Run Unit Tests with ASAN
      env:
        ASAN_OPTIONS: detect_leaks=0,detect_odr_violation=0,allocator_may_return_null=1
      run: |
        export PATH=${HOME}/.local/bin:${PATH}
        meson setup -Dbuildtype=debugoptimized -Db_sanitize=address,undefined build
        meson compile -C build
        build/capn-test
